### ISSUE TITLE
Option should NOT be set on a mere match.

### ISSUE THREAD

**Issue by mlrus** [trevorld/getopt#8]
Documentation claims this is "C-like getopt behavior".   The C routines do not set flags based on prefix match. The R getopt, however, sets flags based on prefix match.

Options opt$bad and opt$badCode both set by **-B**  or **--badCode**. 
Modify example from `help("getopt")`` to add following

``` R
spec = matrix(c(
  'verbose', 'v', 2, "integer",
  'help'   , 'h', 0, "logical",
  'bad'    , 'b', 0, "logical",   ## Should NOT be set by input -B or input --badCode
  'badCode', 'B', 0, "logical",   ## Should set opt$badCode, but not opt$bad
  'count'  , 'c', 1, "integer",
  'mean'   , 'm', 1, "double",
  'sd'     , 's', 1, "double"
), byrow=TRUE, ncol=4);
opt = getopt(spec);
```

Compare with standard C example

``` C
      static struct option long_options[] =
        {
          /* These options set a flag. */
          {"mmpp",    no_argument,       &mmpp_flag, 1 },
          {"mmppClus", no_argument,      &mmppClus_flag, 1 },
          {"verbose", no_argument,       &verbose_flag, 1},
          {"brief",   no_argument,       &verbose_flag, 0},
          /* These options don’t set a flag.
 *              We distinguish them by their indices. */
          {"add",     no_argument,       0, 'a'},
          {"append",  no_argument,       0, 'b'},
          {"delete",  required_argument, 0, 'd'},
          {"create",  required_argument, 0, 'c'},
          {"file",    required_argument, 0, 'f'},
          {0, 0, 0, 0}
        };
```

**Comment by trevorld** [comment]
> Options opt$bad and opt$badCode both set by -B or --badCode. 

I'm confused.  What do you mean by ``opt$bad`` and ``opt$badCode`` both set by ``-B`` or ``--badCode.`` ``badCode`` is only set with ``-B`` or ``--badCode``.  And ``bad`` is only set with ``-b`` or ``--bad``.  Are you using an old version of ``optparse``?  This what I get:

    > library(getopt)
    > spec = matrix(c(
     +   'verbose', 'v', 2, "integer",
     +   'help'   , 'h', 0, "logical",
     +   'bad'    , 'b', 0, "logical",   ## Should NOT be set by input -B or input --badCode
     +   'badCode', 'B', 0, "logical",   ## Should set opt$badCode, but not opt$bad
     +   'count'  , 'c', 1, "integer",
     +   'mean'   , 'm', 1, "double",
     +   'sd'     , 's', 1, "double"
     + ), byrow=TRUE, ncol=4);

    > getopt(spec, "-B")
    $ARGS
    character(0)

    $badCode
     [1] TRUE

     > getopt(spec, "--badCode")
     $ARGS
     character(0)

     $badCode
     [1] TRUE

     > getopt(spec, "--bad")
     $ARGS
    character(0)

     $bad
     [1] TRUE

     > getopt(spec, "-b")
     $ARGS
     character(0)

     $bad
     [1] TRUE

     > 

C-like behaviour is reference that this is much more similar (but not necessarily identical) to a C way of doing things than other option parsers.  I didn't write the package (just maintain it) nor have I used the C version so there very well could be slight differences in behaviour.

**Comment by trevorld** [comment]
Non-reproducible (or unclear?) bug.
