### ISSUE TITLE
short flag overlapping with defaults

### ISSUE THREAD

**Issue by jeffpbruce** [trevorld/getopt#9]
There is small bug where the parse_args() function will crash if any of your options have a short flag that is the same as one of the options that is there by default.  In my case I had an option with the short flag '-h' which overlaps with that of "--help".  I spent some time trying to figure out what was going wrong, so it would be nice if the function gave some indication that you may need to change your short/long flag so it doesn't overlap with the defaults.

**Comment by trevorld** [comment]
Also opening issue in ``optparse`` project.  ``getopt`` doesn't actually create a help option by default but I agree its error message could be a little more helpful.

https://github.com/trevorld/optparse/issues/19

**Comment by trevorld** [comment]
Note you should specify the ``add_help_option=FALSE``` in ``OptionParser`` if you you want to use the `-h` or ``-help`` flags in ``optparse``.  It is expected behaviour for an error to be thrown if multiple short flags are identical (otherwise how can ``getopt`` know which one to use).
